### ISSUE TITLE
Total fare not showing

### ISSUE THREAD

**Issue by MvSerenity** [MvSerenity/Ticket-Fare#1]
Hey i have created a program but the total fare is not showing up please help

**Comment by its-me-piyush** [comment]
I want to work on this issue can you please assign me?

**Comment by Rkpani05** [comment]
Hey it was very small mistake i corrected it

**Comment by MvSerenity** [comment]
> I want to work on this issue can you please assign me?

I havent receive your merge request

**Comment by MvSerenity** [comment]
> Hey it was very small mistake i corrected it

checking it

**Comment by zsiecr** [comment]
yep its right 👍🏻
